# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e9afa137ad0e27662e52877e48d6da365cb297753e9ba554e748a2c4f01fc68235be71c9bac5c8dbe9e90db88a2dda853b4706bcf11d6f409ebe304f6a47479

test:
  secret_key_base: 073eb1084863338fd07228d0994f03c2eec68a1c00659900088bff0ee4466f423f1dfdcae14bbb52a0aa9e4689f06ab5c43a876a55add825ce45fa4d159569ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
